#definir un nom
name: Laravel_CI

#definir les déclencheurs
on:
  push:
    branches: [main]

jobs:
  #définir un runners
  build:
    runs-on: ubuntu-latest
    steps:
      #récupérer le code source
      - name: Récupérer le code source
        uses: actions/checkout@v5
      #tester le code source
      - name: Run test
        run: cd app && composer i && cp .env.example .env && php artisan key:gen && php artisan test

      #si correct construire l'image
      - name: Build app_image
        run: docker build -t willy16/laravel_cicd:latest .

      #se connecter à docker hub
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          


  #pousser l'image en deux versions v1 et latest
